### PR TITLE
Update networking.js

### PR DESCRIPTION
**Pull request by sanderv32**
Fixes issue #34 on OSX.

### CODE REVIEW

**Comment by djMax** [comment]
When I apply this patch I get the EADDRINUSE exception all the time...

**Comment by gregorym** [comment]
Same as @djMax

**Comment by tberthe** [comment]
@djMax @gregorym, what is your OS ? and which version of node / io.js did you use? (I'm working on many modifications of mdns-js and would like to test your case before proposing a pull request))

**Comment by djMax** [comment]
Mac OS and 0.12.2

**Comment by sanderv32** [comment]
On OSX i also get this error, sorry guys will have to look into this again.

**Comment by kmpm** [comment]
Changes that cover this is already implemented or tackled elsewhere

**Pull request closed without merging**
